//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conference
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Conference()
        {
            this.ConferenceMembers = new HashSet<ConferenceMember>();
            this.ConferenceTopics = new HashSet<ConferenceTopic>();
            this.Papers = new HashSet<Paper>();
            this.RegisterRequests = new HashSet<RegisterRequest>();
        }
    
        public int confId { get; set; }
        public Nullable<int> chairId { get; set; }
        public string confTitle { get; set; }
        public string confLocation { get; set; }
        public Nullable<System.DateTime> confBeginDate { get; set; }
        public Nullable<System.DateTime> confEndDate { get; set; }
        public Nullable<System.DateTime> paperDeadline { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConferenceMember> ConferenceMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConferenceTopic> ConferenceTopics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paper> Papers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegisterRequest> RegisterRequests { get; set; }
    }
}
