//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expertise
    {
        public int Id { get; set; }
        public int userId { get; set; }
        public int keywrdId { get; set; }
    
        public virtual Keyword Keyword { get; set; }
        public virtual User User { get; set; }
    }
}
