//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paper()
        {
            this.Feedbacks = new HashSet<Feedback>();
            this.PaperReviews = new HashSet<PaperReview>();
            this.PaperTopics = new HashSet<PaperTopic>();
        }
    
        public int paperId { get; set; }
        public string paperTitle { get; set; }
        public string paperAuthor { get; set; }
        public Nullable<System.DateTime> paperSubDate { get; set; }
        public string paperLength { get; set; }
        public byte[] paperContent { get; set; }
        public int confId { get; set; }
        public Nullable<int> auId { get; set; }
        public string paperFormat { get; set; }
        public string paperStatus { get; set; }
        public string paperFileName { get; set; }
    
        public virtual Conference Conference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaperReview> PaperReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaperTopic> PaperTopics { get; set; }
    }
}
